version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - intellibus-network

  backend:
    build: ./backend
    ports:
      - "5000:8000"
    networks:
      - intellibus-network

  ai:
    build: ./AI
    ports:
      - "8000:8000"
    networks:
      - intellibus-network

networks:
  intellibus-network: