version: '3'

services:
  frontend:
    image: $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/my-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    networks:
      - intellibus-network

  backend:
    image: $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/my-backend:latest
    ports:
      - "5000:8000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - intellibus-network

  ai:
    image: $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/my-ai:latest
    ports:
      - "8000:8000"
    networks:
      - intellibus-network

networks:
  intellibus-network:
