name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-to-ecr
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push Docker images
      run: |
        docker build -t my-frontend:latest ./frontend
        docker build -t my-backend:latest ./backend
        docker build -t my-ai:latest ./AI

    - name: Deploy with Docker Compose
      uses: docker/compose-action@v2
      with:
        filename: docker-compose.yml
        project_name: intellibus-kids
        push: true